version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 18
  build:
    commands:
      - cd frontend
      - npm install
      - npm run build
      - aws s3 cp ./dist s3://$FRONTEND_BUCKET/ --recursive
      - cd ../sam-backend
      - sam build
      - sam package --s3-bucket $ARTIFACT_BUCKET --output-template-file packaged.yml --no-resolve-s3

artifacts:
  files:
    - sam-backend/packaged.yml
  discard-paths: yes