version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 18
  build:
    commands:
      - cd frontend
      - npm install
      - npm run build
      - cd ../sam-backend
      - sam build
      - cd ..
      - cp -r frontend/dist ./
      - cp -r sam-backend/.aws-sam/build ./sam

artifacts:
  files:
    - dist/**/*
    - sam/**/*