version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 18
  build:
    commands:
      - cd frontend
      - npm install
      - npm run build
      - cd ../sam-backend
      - sam build
      - cd ..
      - zip -r frontend/dist.zip frontend/dist/*
      - zip -r sam-backend/.aws-sam/sam.zip sam-backend/.aws-sam/build/*

artifacts:
  files:
    - frontend/dist.zip
    - sam-backend/.aws-sam/sam.zip
  discard-paths: yes