version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 18
  build:
    commands:
      - cd frontend
      - npm install
      - npm run build
      - cd ../sam-backend
      - sam build

artifacts:
  files:
    - frontend/dist/**/*
    - sam-backend/.aws-sam/build/**/*
  discard-paths: yes
